#!/usr/bin/env python3
"""Send failing pytest results to Claude for automated fix suggestions."""

from __future__ import annotations

import argparse
import json
import os
import sys
import textwrap
from pathlib import Path
from typing import Any, Dict, List

# Add ci directory to path to enable imports
sys.path.insert(0, str(Path(__file__).parent))

from api import send_to_claude, send_health_check, resolve_model_name
from config import BASE_ANALYSIS_PROMPT
from file_utils import read_source
from pytest import (
    load_report,
    extract_failures,
    format_longrepr,
    extract_response_text,
    build_comment_section,
)


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--report",
        default=".report.json",
        help="Path to the pytest JSON report generated by pytest-json-report.",
    )
    parser.add_argument(
        "--comment-file",
        default=None,
        help="If provided, write a Markdown summary suitable for a PR comment to this path.",
    )
    return parser.parse_args()


def build_payload(failure: Dict[str, Any], report: Dict[str, Any], index: int) -> Dict[str, Any]:
    """Build API payload for Claude from test failure."""
    longrepr = failure.get("longrepr")
    reprcrash = longrepr.get("reprcrash") if isinstance(longrepr, dict) else None
    source_path = reprcrash.get("path") if isinstance(reprcrash, dict) else None
    source_code = read_source(source_path)
    traceback_text = format_longrepr(longrepr)

    failure_json = json.dumps(failure, indent=2, ensure_ascii=False)
    report_json = json.dumps(report, indent=2, ensure_ascii=False)

    rel_path = source_path
    if source_path:
        try:
            rel_path = os.path.relpath(Path(source_path).resolve(), Path.cwd())
        except OSError:
            rel_path = source_path

    body = textwrap.dedent(
        f"""
        {BASE_ANALYSIS_PROMPT}

        ### Failing Test #{index}
        - **Node ID:** {failure.get('nodeid', 'unknown')}
        - **Test Outcome:** {failure.get('outcome')}
        - **Source File:** {rel_path or 'unknown'}

        ### Python Source Code
        ```python
        {source_code}
        ```

        ### Pytest JSON Report (failing test excerpt)
        ```json
        {failure_json}
        ```

        ### Full Pytest JSON Report
        ```json
        {report_json}
        ```

        ### Traceback and Error Messages
        ```
        {traceback_text}
        ```
        """
    ).strip()

    return {
        "model": resolve_model_name(),
        "max_tokens": 4096,
        "messages": [
            {
                "role": "user",
                "content": body,
            }
        ]
    }


def main() -> None:
    """Main entry point for claude_report."""
    args = parse_args()
    report = load_report(args.report)
    failures = extract_failures(report)

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    model_name = resolve_model_name()

    print(f"Using Claude model: {model_name}")

    # Handle case with no failures
    if not failures:
        summary = report.get("summary", {})
        errors = summary.get("errors") or 0
        if errors:
            print("Pytest did not record any failing tests, but collection errors were reported.")
        else:
            print("All tests passed. No failing tests were recorded.")

        if not api_key:
            print("ANTHROPIC_API_KEY environment variable is not set; skipping Claude health check.")
            return

        send_health_check(api_key, model_name)
        return

    # Ensure API key is available
    if not api_key:
        print("ANTHROPIC_API_KEY environment variable is not set.", file=sys.stderr)
        raise SystemExit(1)

    # Process all failures
    comment_sections: List[str] = []

    for index, failure in enumerate(failures, start=1):
        payload = build_payload(failure, report, index)
        print(f"Sending failure #{index} to Claude...")
        response = send_to_claude(api_key, payload)
        print(json.dumps(response, indent=2, ensure_ascii=False))

        comment_body = extract_response_text(response)
        if comment_body:
            comment_sections.append(build_comment_section(failure, comment_body))

    # Write comment file if requested
    if args.comment_file and comment_sections:
        comment_text = "\n\n---\n\n".join(comment_sections).strip()
        comment_path = Path(args.comment_file)
        comment_path.write_text(f"{comment_text}\n", encoding="utf-8")
        print(f"Claude analysis written to {comment_path}")
    elif args.comment_file:
        comment_path = Path(args.comment_file)
        if comment_path.exists():
            comment_path.unlink()
        print("No Claude analysis generated; comment file removed if it existed.")


if __name__ == "__main__":
    main()
