#!/usr/bin/env python3
"""Send failing pytest results to Claude for automated fix suggestions."""

from __future__ import annotations

import argparse
import json
import os
import sys
import textwrap
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any, Dict, List, Optional

API_BASE_URL = "https://api.anthropic.com/v1/messages"
ANTHROPIC_VERSION = "2023-06-01"
DEFAULT_CLAUDE_MODEL = "claude-sonnet-4-5-20250929"  # Sonnet 4.5
FALLBACK_MODELS = ["claude-sonnet-4-20250514", "claude-3-5-sonnet-20241022"]

BASE_PROMPT = textwrap.dedent(
    """
    You are an advanced automated code-repair agent integrated into a CI pipeline.
    Your task is to analyze Python test results and propose precise code fixes.

    ### INPUT PROVIDED TO YOU:
    1. **Python source code** (the file that caused the test failure).
    2. **Test results in JSON format** generated by pytest-json-report.
    3. **Complete traceback and error messages**.

    ### YOUR GOALS:
    - Identify the exact root cause of the failure.
    - Explain the issue clearly and concisely.
    - Suggest specific improvements or corrections to the code.
    - Provide a minimal, self-contained patch that fixes the problem.
    - Ensure the patch follows Python best practices (PEP8, readability, robustness).
    - Do NOT modify code unrelated to the failure unless needed for correctness.
    - Do NOT invent new tests; use only the failing information provided.

    ### REQUIRED OUTPUT FORMAT:
    You must respond using this structure:

    1. **Root Cause Analysis**
       - Explain why the failure happened.
       - Reference the exact line(s) of code responsible.
       - Summarize how the bug manifests.

    2. **Recommended Fix**
       - Explain conceptually what change must be made to correct the issue.

    3. **Proposed Patch (unified diff format)**
       - Provide ONLY a valid unified diff.
       - It must apply cleanly to the original file.
       - Example format:
         ```diff
         --- file.py
         +++ file.py
         @@ -10,6 +10,8 @@
         ```
       - Keep patch minimal and directly related to the fix.

    4. **Post-Fix Expectations**
       - Briefly describe how the fix will make the tests pass.

    ### IMPORTANT RULES:
    - Do NOT rewrite entire files.
    - Do NOT output explanations inside the diff.
    - Do NOT hallucinate APIs or functions that do not exist.
    - Keep changes tight, safe, and explainable.
    - Prioritize correctness over style refactoring—unless the failure is caused by style issues.

    Additionally, generate guidance that can be used to open a dedicated GitHub pull request for
    each failing test. Never combine fixes for multiple files or functions into a single pull
    request; each response must focus on a single failing scenario.

    Now wait for the JSON test report and the code before producing results.
    """
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--report",
        default=".report.json",
        help="Path to the pytest JSON report generated by pytest-json-report.",
    )
    parser.add_argument(
        "--comment-file",
        default=None,
        help="If provided, write a Markdown summary suitable for a PR comment to this path.",
    )
    return parser.parse_args()


def load_report(path: str) -> Dict[str, Any]:
    try:
        with open(path, "r", encoding="utf-8") as report_file:
            return json.load(report_file)
    except FileNotFoundError as exc:
        print(f"Pytest JSON report not found at {path}: {exc}", file=sys.stderr)
        raise SystemExit(1)


def extract_failures(report: Dict[str, Any]) -> List[Dict[str, Any]]:
    return [test for test in report.get("tests", []) if test.get("outcome") == "failed"]


def extract_response_text(response: Dict[str, Any]) -> str:
    """Extract concatenated text from the Claude response."""

    texts: List[str] = []
    content = response.get("content", [])

    for block in content:
        if block.get("type") == "text":
            text = block.get("text", "")
            if text.strip():
                texts.append(text.strip())

    combined = "\n\n".join(texts).strip()
    return combined


def build_comment_section(failure: Dict[str, Any], body: str) -> str:
    """Generate a Markdown section for a specific failing test."""

    nodeid = failure.get("nodeid") or failure.get("name") or "failing test"
    header = f"### Claude analysis for `{nodeid}`"
    return f"{header}\n\n{body.strip()}"


def format_longrepr(longrepr: Any) -> str:
    if isinstance(longrepr, str):
        return longrepr
    if not isinstance(longrepr, dict):
        return json.dumps(longrepr, indent=2, ensure_ascii=False)

    lines: List[str] = []

    reprtraceback = longrepr.get("reprtraceback")
    if isinstance(reprtraceback, dict):
        for entry in reprtraceback.get("reprentries", []):
            data = entry.get("data")
            if data:
                lines.append(data)
            file_loc = entry.get("reprfileloc")
            if isinstance(file_loc, dict):
                path = file_loc.get("path")
                lineno = file_loc.get("lineno")
                message = file_loc.get("message")
                location = ":".join(
                    str(part)
                    for part in (path, lineno, message)
                    if part not in (None, "")
                )
                if location:
                    lines.append(location)

    reprcrash = longrepr.get("reprcrash")
    if isinstance(reprcrash, dict):
        crash_path = reprcrash.get("path")
        crash_lineno = reprcrash.get("lineno")
        crash_message = reprcrash.get("message")
        crash_line = ":".join(
            str(part) for part in (crash_path, crash_lineno, crash_message) if part not in (None, "")
        )
        if crash_line:
            lines.append(crash_line)

    sections = longrepr.get("sections")
    if isinstance(sections, list):
        for section in sections:
            if isinstance(section, list) and len(section) == 2:
                title, content = section
                lines.append(f"{title}\n{content}")

    return "\n".join(lines)


def read_source(path: Optional[str]) -> str:
    if not path:
        return "<Source path not provided by pytest>"

    repo_root = Path.cwd()
    resolved_path = Path(path)
    if not resolved_path.is_absolute():
        resolved_path = (repo_root / resolved_path).resolve()

    if not resolved_path.exists():
        return f"<Unable to locate source file at {resolved_path}>"

    try:
        return resolved_path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return resolved_path.read_text(encoding="latin-1")


def build_payload(failure: Dict[str, Any], report: Dict[str, Any], index: int) -> Dict[str, Any]:
    longrepr = failure.get("longrepr")
    reprcrash = longrepr.get("reprcrash") if isinstance(longrepr, dict) else None
    source_path = reprcrash.get("path") if isinstance(reprcrash, dict) else None
    source_code = read_source(source_path)
    traceback_text = format_longrepr(longrepr)

    failure_json = json.dumps(failure, indent=2, ensure_ascii=False)
    report_json = json.dumps(report, indent=2, ensure_ascii=False)

    rel_path = source_path
    if source_path:
        try:
            rel_path = os.path.relpath(Path(source_path).resolve(), Path.cwd())
        except OSError:
            rel_path = source_path

    body = textwrap.dedent(
        f"""
        {BASE_PROMPT}

        ### Failing Test #{index}
        - **Node ID:** {failure.get('nodeid', 'unknown')}
        - **Test Outcome:** {failure.get('outcome')}
        - **Source File:** {rel_path or 'unknown'}

        ### Python Source Code
        ```python
        {source_code}
        ```

        ### Pytest JSON Report (failing test excerpt)
        ```json
        {failure_json}
        ```

        ### Full Pytest JSON Report
        ```json
        {report_json}
        ```

        ### Traceback and Error Messages
        ```
        {traceback_text}
        ```
        """
    ).strip()

    return {
        "model": resolve_model_name(),
        "max_tokens": 4096,
        "messages": [
            {
                "role": "user",
                "content": body,
            }
        ]
    }


def normalize_model_name(model_name: str) -> str:
    """Ensure the Claude model name is valid."""
    return model_name.strip()


def resolve_model_name() -> str:
    """Return the Claude model name, allowing override via CLAUDE_MODEL."""

    configured_name = os.environ.get("CLAUDE_MODEL", DEFAULT_CLAUDE_MODEL)
    if not configured_name or not configured_name.strip():
        configured_name = DEFAULT_CLAUDE_MODEL
    return normalize_model_name(configured_name)


def iter_candidate_models(model_name: str):
    """Yield model name variants to improve compatibility."""

    yielded = set()

    # Try original model first
    if model_name and model_name not in yielded:
        yielded.add(model_name)
        yield model_name

    # Then try fallback models
    for fallback in FALLBACK_MODELS:
        if fallback not in yielded:
            yielded.add(fallback)
            yield fallback


def send_to_claude(api_key: str, payload: Dict[str, Any]) -> Dict[str, Any]:
    """Send request to Claude API with retry logic."""

    errors = []
    model_name = payload.get("model", DEFAULT_CLAUDE_MODEL)

    for current_model in iter_candidate_models(model_name):
        # Update payload with current model
        current_payload = payload.copy()
        current_payload["model"] = current_model

        print(f"Attempting Claude request using model: {current_model}")

        headers = {
            "Content-Type": "application/json",
            "x-api-key": api_key,
            "anthropic-version": ANTHROPIC_VERSION,
        }

        request = urllib.request.Request(
            API_BASE_URL,
            data=json.dumps(current_payload).encode("utf-8"),
            headers=headers,
            method="POST",
        )

        try:
            with urllib.request.urlopen(request, timeout=120) as response:
                return json.load(response)
        except urllib.error.HTTPError as exc:
            error_detail = exc.read().decode("utf-8", errors="replace")
            message = (
                f"Claude API request failed with model {current_model}: {exc.code} {exc.reason}\n{error_detail}"
            )
            print(message, file=sys.stderr)

            # 529 means overloaded, worth retrying
            if exc.code == 529:
                print("Model overloaded, waiting before retry...", file=sys.stderr)
                time.sleep(2)
                # Retry once for overloaded
                try:
                    request = urllib.request.Request(
                        API_BASE_URL,
                        data=json.dumps(current_payload).encode("utf-8"),
                        headers=headers,
                        method="POST",
                    )
                    with urllib.request.urlopen(request, timeout=120) as response:
                        return json.load(response)
                except Exception as retry_exc:
                    print(f"Retry failed: {retry_exc}", file=sys.stderr)

            errors.append(message)
        except urllib.error.URLError as exc:
            message = f"Failed to reach Claude API with model {current_model}: {exc}"
            print(message, file=sys.stderr)
            errors.append(message)
        except Exception as exc:
            message = f"Unexpected error with model {current_model}: {exc}"
            print(message, file=sys.stderr)
            errors.append(message)

    print("All Claude API attempts failed.", file=sys.stderr)
    if errors:
        print("\nErrors encountered:", file=sys.stderr)
        for error in errors[:3]:  # Show first 3 errors
            print(f"  - {error}", file=sys.stderr)
    raise SystemExit(1)


def send_health_check_prompt(api_key: str, model_name: Optional[str] = None) -> None:
    """Send a minimal prompt to verify Claude connectivity."""

    resolved_model = model_name or resolve_model_name()

    payload = {
        "model": resolved_model,
        "max_tokens": 10,
        "messages": [
            {
                "role": "user",
                "content": "1+1. Answer with only one number, nothing more.",
            }
        ]
    }

    print(
        "No failing tests were captured. Sending Claude health check prompt using "
        f"model '{resolved_model}'..."
    )
    response = send_to_claude(api_key, payload)
    print("Claude health check response:")
    print(json.dumps(response, indent=2, ensure_ascii=False))


def main() -> None:
    args = parse_args()
    report = load_report(args.report)
    failures = extract_failures(report)

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    model_name = resolve_model_name()

    print(f"Using Claude model: {model_name}")

    if not failures:
        summary = report.get("summary", {})
        errors = summary.get("errors") or 0
        if errors:
            print(
                "Pytest did not record any failing tests, but collection errors were reported."
            )
        else:
            print("All tests passed. No failing tests were recorded.")

        if not api_key:
            print("ANTHROPIC_API_KEY environment variable is not set; skipping Claude health check.")
            return

        send_health_check_prompt(api_key, model_name)
        return

    if not api_key:
        print("ANTHROPIC_API_KEY environment variable is not set.", file=sys.stderr)
        raise SystemExit(1)

    comment_sections: List[str] = []

    for index, failure in enumerate(failures, start=1):
        payload = build_payload(failure, report, index)
        print(f"Sending failure #{index} to Claude...")
        response = send_to_claude(api_key, payload)
        print(json.dumps(response, indent=2, ensure_ascii=False))

        comment_body = extract_response_text(response)
        if comment_body:
            comment_sections.append(build_comment_section(failure, comment_body))

    if args.comment_file and comment_sections:
        comment_text = "\n\n---\n\n".join(comment_sections).strip()
        comment_path = Path(args.comment_file)
        comment_path.write_text(f"{comment_text}\n", encoding="utf-8")
        print(f"Claude analysis written to {comment_path}")
    elif args.comment_file:
        comment_path = Path(args.comment_file)
        if comment_path.exists():
            comment_path.unlink()
        print("No Claude analysis generated; comment file removed if it existed.")


if __name__ == "__main__":
    main()
