#!/usr/bin/env python3
"""Send failing pytest results to Gemini for automated fix suggestions."""

from __future__ import annotations

import argparse
import json
import os
import sys
import textwrap
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any, Dict, List, Optional

API_URL = (
    "https://generativelanguage.googleapis.com/v1beta/models/"
    "gemini-1.5-pro-latest:generateContent"
)

BASE_PROMPT = textwrap.dedent(
    """
    You are an advanced automated code-repair agent integrated into a CI pipeline.
    Your task is to analyze Python test results and propose precise code fixes.

    ### INPUT PROVIDED TO YOU:
    1. **Python source code** (the file that caused the test failure).
    2. **Test results in JSON format** generated by pytest-json-report.
    3. **Complete traceback and error messages**.

    ### YOUR GOALS:
    - Identify the exact root cause of the failure.
    - Explain the issue clearly and concisely.
    - Suggest specific improvements or corrections to the code.
    - Provide a minimal, self-contained patch that fixes the problem.
    - Ensure the patch follows Python best practices (PEP8, readability, robustness).
    - Do NOT modify code unrelated to the failure unless needed for correctness.
    - Do NOT invent new tests; use only the failing information provided.

    ### REQUIRED OUTPUT FORMAT:
    You must respond using this structure:

    1. **Root Cause Analysis**
       - Explain why the failure happened.
       - Reference the exact line(s) of code responsible.
       - Summarize how the bug manifests.

    2. **Recommended Fix**
       - Explain conceptually what change must be made to correct the issue.

    3. **Proposed Patch (unified diff format)**
       - Provide ONLY a valid unified diff.
       - It must apply cleanly to the original file.
       - Example format:
         ```diff
         --- file.py
         +++ file.py
         @@ -10,6 +10,8 @@
         ```
       - Keep patch minimal and directly related to the fix.

    4. **Post-Fix Expectations**
       - Briefly describe how the fix will make the tests pass.

    ### IMPORTANT RULES:
    - Do NOT rewrite entire files.
    - Do NOT output explanations inside the diff.
    - Do NOT hallucinate APIs or functions that do not exist.
    - Keep changes tight, safe, and explainable.
    - Prioritize correctness over style refactoring—unless the failure is caused by style issues.

    Additionally, generate guidance that can be used to open a dedicated GitHub pull request for
    each failing test. Never combine fixes for multiple files or functions into a single pull
    request; each response must focus on a single failing scenario.

    Now wait for the JSON test report and the code before producing results.
    """
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--report",
        default=".report.json",
        help="Path to the pytest JSON report generated by pytest-json-report.",
    )
    return parser.parse_args()


def load_report(path: str) -> Dict[str, Any]:
    try:
        with open(path, "r", encoding="utf-8") as report_file:
            return json.load(report_file)
    except FileNotFoundError as exc:
        print(f"Pytest JSON report not found at {path}: {exc}", file=sys.stderr)
        raise SystemExit(1)


def extract_failures(report: Dict[str, Any]) -> List[Dict[str, Any]]:
    return [test for test in report.get("tests", []) if test.get("outcome") == "failed"]


def format_longrepr(longrepr: Any) -> str:
    if isinstance(longrepr, str):
        return longrepr
    if not isinstance(longrepr, dict):
        return json.dumps(longrepr, indent=2, ensure_ascii=False)

    lines: List[str] = []

    reprtraceback = longrepr.get("reprtraceback")
    if isinstance(reprtraceback, dict):
        for entry in reprtraceback.get("reprentries", []):
            data = entry.get("data")
            if data:
                lines.append(data)
            file_loc = entry.get("reprfileloc")
            if isinstance(file_loc, dict):
                path = file_loc.get("path")
                lineno = file_loc.get("lineno")
                message = file_loc.get("message")
                location = ":".join(
                    str(part)
                    for part in (path, lineno, message)
                    if part not in (None, "")
                )
                if location:
                    lines.append(location)

    reprcrash = longrepr.get("reprcrash")
    if isinstance(reprcrash, dict):
        crash_path = reprcrash.get("path")
        crash_lineno = reprcrash.get("lineno")
        crash_message = reprcrash.get("message")
        crash_line = ":".join(
            str(part) for part in (crash_path, crash_lineno, crash_message) if part not in (None, "")
        )
        if crash_line:
            lines.append(crash_line)

    sections = longrepr.get("sections")
    if isinstance(sections, list):
        for section in sections:
            if isinstance(section, list) and len(section) == 2:
                title, content = section
                lines.append(f"{title}\n{content}")

    return "\n".join(lines)


def read_source(path: Optional[str]) -> str:
    if not path:
        return "<Source path not provided by pytest>"

    repo_root = Path.cwd()
    resolved_path = Path(path)
    if not resolved_path.is_absolute():
        resolved_path = (repo_root / resolved_path).resolve()

    if not resolved_path.exists():
        return f"<Unable to locate source file at {resolved_path}>"

    try:
        return resolved_path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return resolved_path.read_text(encoding="latin-1")


def build_payload(failure: Dict[str, Any], report: Dict[str, Any], index: int) -> Dict[str, Any]:
    longrepr = failure.get("longrepr")
    reprcrash = longrepr.get("reprcrash") if isinstance(longrepr, dict) else None
    source_path = reprcrash.get("path") if isinstance(reprcrash, dict) else None
    source_code = read_source(source_path)
    traceback_text = format_longrepr(longrepr)

    failure_json = json.dumps(failure, indent=2, ensure_ascii=False)
    report_json = json.dumps(report, indent=2, ensure_ascii=False)

    rel_path = source_path
    if source_path:
        try:
            rel_path = os.path.relpath(Path(source_path).resolve(), Path.cwd())
        except OSError:
            rel_path = source_path

    body = textwrap.dedent(
        f"""
        {BASE_PROMPT}

        ### Failing Test #{index}
        - **Node ID:** {failure.get('nodeid', 'unknown')}
        - **Test Outcome:** {failure.get('outcome')}
        - **Source File:** {rel_path or 'unknown'}

        ### Python Source Code
        ```python
        {source_code}
        ```

        ### Pytest JSON Report (failing test excerpt)
        ```json
        {failure_json}
        ```

        ### Full Pytest JSON Report
        ```json
        {report_json}
        ```

        ### Traceback and Error Messages
        ```
        {traceback_text}
        ```
        """
    ).strip()

    return {
        "contents": [
            {
                "role": "user",
                "parts": [
                    {
                        "text": body,
                    }
                ],
            }
        ]
    }


def send_to_gemini(api_key: str, payload: Dict[str, Any]) -> Dict[str, Any]:
    request = urllib.request.Request(
        f"{API_URL}?key={api_key}",
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            return json.load(response)
    except urllib.error.HTTPError as exc:
        error_detail = exc.read().decode("utf-8", errors="replace")
        print(f"Gemini API request failed: {exc.code} {exc.reason}\n{error_detail}", file=sys.stderr)
        raise SystemExit(1)
    except urllib.error.URLError as exc:
        print(f"Failed to reach Gemini API: {exc}", file=sys.stderr)
        raise SystemExit(1)


def main() -> None:
    args = parse_args()
    report = load_report(args.report)
    failures = extract_failures(report)

    if not failures:
        print("All tests passed. No data sent to Gemini.")
        return

    api_key = os.environ.get("GEMINI_KEY")
    if not api_key:
        print("GEMINI_KEY environment variable is not set.", file=sys.stderr)
        raise SystemExit(1)

    for index, failure in enumerate(failures, start=1):
        payload = build_payload(failure, report, index)
        print(f"Sending failure #{index} to Gemini...")
        response = send_to_gemini(api_key, payload)
        print(json.dumps(response, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
